prefix cpmeta: <http://meta.icos-cp.eu/ontologies/cpmeta/>
construct{
	?prod rdfs:comment ?comm .
}
from <http://meta.icos-cp.eu/resources/ecocsv/>
where{
	?prod a cpmeta:DataProduction .
	?prod rdfs:comment ?comm .
	filter(contains(?comm, "r>"))
}
